org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.java.installations.auto-download=true

mod_version=3.1.0
maven_group=dev.inputbooster
archives_base_name=inputbooster-api

minecraft_version=1.21.11
minecraft_version_range=>=1.21 <1.22
yarn_mappings=1.21.11+build.6
loader_version=0.19.2
junit_version=5.11.4
junit_platform_version=1.11.4
